---
kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: git

steps:
  - name: build
    image: docker
    privileged: true
    environment: 
      TOKEN:
        from_secret: registry_token
    commands:
      - dockerd &
      - docker login -u registry -p $TOKEN registry.v0l.io
      - docker buildx build --push -t registry.v0l.io/nests-backend:latest -f NestsBackend/Dockerfile .
      - kill $(cat /var/run/docker.pid)